### PR TITLE
#6: Wrap in a test for Entity Plus

### PR DESCRIPTION
**Pull request by laryn**

### CODE REVIEW

**Comment by laryn** [comment]
This looks like a lot of change in the diff but it's really just wrapping everything in `if (!module_exists('entity_plus')) {` and indented one level deeper.

**Comment by herbdool** [comment]
Looks like a dirty but good solution. Maybe to make the diff look cleaner, you could have this at beginning instead:
```
if (module_exists('entity_plus')) {
  return;
}
```

I think that'll just skip rest of file and not exit whole application.

**Comment by laryn** [comment]
Nice suggestion, @herbdool -- thanks. Diff looks a lot cleaner now.

**Comment by herbdool** [comment]
@laryn does this PR still work for you?

**Comment by herbdool** [comment]
@laryn I tested. My suggestion doesn't work since it seems to read the whole file anyway and then still get the fatal error. So I think your approach, while "messier", is still the best.

**Comment by laryn** [comment]
@herbdool Thanks and sorry I haven't tested -- this week is a bit overfull.

**Comment by docwilmot** [comment]
Would this work?

```
if (module_exists('entity_plus')) {
  exit();
}
```

And @laryn and @herbdool thanks for all your work on this. Feel free to merge as you see fit. I'm a bit tied up and I suspect this may hold back all the other modules needing to switch to Entity Plus.

**Comment by herbdool** [comment]
@docwilmot I haven't tried that. I assumed it would stop everything. I think I might merge this.

**Pull request merged**
